//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAME.Desktop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Modules")]
        public string DefaultPluginPath {
            get {
                return ((string)(this["DefaultPluginPath"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.\Modules</string>
  <string>..\Modules</string>
  <string>..\..\..\GAME\Modules</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UserPluginPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UserPluginPaths"]));
            }
            set {
                this["UserPluginPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GAME.Modules.*.dll")]
        public string DefaultPluginPattern {
            get {
                return ((string)(this["DefaultPluginPattern"]));
            }
            set {
                this["DefaultPluginPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPluginPattern {
            get {
                return ((string)(this["UserPluginPattern"]));
            }
            set {
                this["UserPluginPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Modules")]
        public string UserPluginPath {
            get {
                return ((string)(this["UserPluginPath"]));
            }
            set {
                this["UserPluginPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection UserLaunchedModules {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UserLaunchedModules"]));
            }
            set {
                this["UserLaunchedModules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RememberOpenedModules {
            get {
                return ((bool)(this["RememberOpenedModules"]));
            }
            set {
                this["RememberOpenedModules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::GAME.Common.Core.Models.Settings.Option ModulePattern {
            get {
                return ((global::GAME.Common.Core.Models.Settings.Option)(this["ModulePattern"]));
            }
            set {
                this["ModulePattern"] = value;
            }
        }
    }
}
